import { createActions } from "../../../lib/lodash/reduxUtils";

const types = [
  "CANCEL_REQUEST",
  "INIT",
  "ADD_NOTICE",
  "CLOSE_NOTICE",
  "EMPTY_ACTION",

  "ADD_COMPONENT",
  "PAGE_CHANGE",
  "PAGE_CHANGE_FULFILLED",
  "SECTION_CHANGE",
  "SECTION_CHANGE_FULFILLED",
  "LOGIN_REDIRECT",
  "CHANGE_FOCUSED_INPUT",
  "CHANGE_DATE_RANGE",
  "CHANGE_DATE_RANGE_FULFILLED",
  "DATA_CHANGED",
  "DATA_CHANGE_ERROR",
  "FIND_DATA",
  "PIPELINE",
  "QUEUE_DOWNLOAD_REPORT",
  "START_DOWNLOAD_REPORT",
  "DOWNLOAD_REPORT_FAILED",
  "DOWNLOAD_REPORT_PROGRESS",
  "DOWNLOAD_REPORT_FULFILLED",
  "FETCH_DATA",
  "FETCH_DATA_ERROR",
  "FETCH_DATA_SUCCESS",

  "POLLING_START",
  "POLLING_PAUSE_TOGGLE",
  "POLLING_STOP",
  "POLLING_UPDATE",
  "TOGGLE_QUICK_DATE",
  "TOGGLE_SIDEBAR",
  "TOGGLE_ORDER_BY",
  "LOAD_PROGRESS",
  "LOAD_START",
  "LOAD_FULFILLED",
  "DOWNLOAD_DATA",
  "DOWNLOAD_DATA_ERROR",
  "DOWNLOAD_DATA_FULFILLED",

  "NOTIFY_ERROR",
  "NOTIFY_USER",
  "CLEAR_NOTIFICATION",
  "FETCH_MODEL_INFO",
  "FETCH_MODEL_INFO_ERROR",
  "FETCH_MODEL_INFO_FULFILLED"
];
const actionTypes = types.reduce((acc, c) => ({ ...acc, [c]: c }), {});
const actionCreators = createActions(types);
